version: "3.9"

services:
  postgres:
    image: postgres:17
    container_name: postgresForMaybank
    ports:
      - "127.0.0.1:15432:5432"
    environment:
      POSTGRES_PASSWORD: abc123
      POSTGRES_USER: admin
      POSTGRES_DB: maybank
    command: >
      postgres -c shared_preload_libraries='pg_stat_statements'
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
